### ISSUE TITLE
iCal feed not visible when there are no upcoming events

### ISSUE THREAD

**Issue by lunohodov** [lunohodov/eventical#122]
When there are no upcoming events, people can not subscribe to the iCal feed as it is not visible.

**Comment by afarazit** [comment]
@lunohodov also tried to connect to google calendar and no events were visible.

**Comment by lunohodov** [comment]
Did you use the iCal link as described [here](https://support.google.com/calendar/answer/37083#link)?

<img width="683" alt="Screenshot 2019-05-23 at 20 34 29" src="https://user-images.githubusercontent.com/37100/58277651-7b628300-7d9a-11e9-8583-ddb82ef15ba7.png">

Can you provide more details about the steps you go through?

**Comment by afarazit** [comment]
@lunohodov Oh didn't notice that link. Yes ical work perfectly.
