### ISSUE TITLE
No upcoming events

### ISSUE THREAD

**Issue by sonicj** [lunohodov/eventical#538]
**Describe the bug**
I have authorized a character but when I click on browser, under the select your feed, I get the message "You have no upcoming events". There are events on the characters calendar in game.

**To Reproduce**
1. Go to https://www.eve-calendars.com/
2. Click on Log in with Eve, choose character and authorize.
3. On https://www.eve-calendars.com/calendar, under Subscribe to all events in your EVE Online calendar via… click on browser
4. See You have no upcoming events. This also applies to using Outlook. No events.
5. I have created multiple events on the characters calendar

**Expected behavior**
I expect to see the calendar events

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 202

**Comment by sonicj** [comment]
I am guessing it updates after downtime as events I added to the calendar in game yesterday are showing today, but the one I added today is not showing yet. Is this the expected behavior or should it update immediately?

**Comment by lunohodov** [comment]
@sonicj Welcome and sorry for the late reply!

Currently events update once per day. Do you need events to update more often? If yes, then can you describe the situation?

**Comment by sonicj** [comment]
No once per day is fine. I just did not understand that it worked that way.
Thanks.
